### ISSUE TITLE
amd64-linux-gcc-3.4.4: Command not found

### ISSUE THREAD

**Issue by Llnfeng** [upx/upx-stubtools#2]
use upx-stubtools  compile stub ,then got error amd64-linux-gcc-3.4.4: Command not found,
OS: ubuntu-20.04  
cpu:x86_84

$ cd
$ mkdir -p local/bin
$ cd local/bin
$ wget https://github.com/upx/upx-stubtools/releases/download/v20160918/bin-upx-20160918.tar.xz
$tar xvf bin-upx-20160918.tar.xz
$ mv bin-upx-20160918 bin-upx
$  cd 
$ cd upx-3.96/src/stub/src
$ make all
upx-stubtools-check-version 20160918
amd64-linux-gcc-3.4.4 -fPIC -m64 -nostdinc -MMD -MT amd64-darwin.dylib-entry.h -fno-exceptions -fno-asynchronous-unwind-tables -Wall -W -Wcast-align -Wcast-qual -Wstrict-prototypes -Wwrite-strings -Werror -c src/amd64-darwin.dylib-entry.S -o tmp/amd64-darwin.dylib-entry.bin
make: amd64-linux-gcc-3.4.4: Command not found
make: *** [Makefile:305: amd64-darwin.dylib-entry.h] Error 127
what confused me is  amd64-linux-gcc-3.4.4 is in bin-upx ,but not found

**Comment by Llnfeng** [comment]
j解决问题了，参考路径如下https://samsclass.info/126/proj/PMA131a.htm

**Comment by ygm521** [comment]
我是debian系统，这个咋回事呢？
![image](https://github.com/upx/upx-stubtools/assets/7271089/e0613ba1-3244-40ff-b382-984ffc92677f)
